#!/usr/bin/python

#Code reads the file named 'analysis.txt' and depending on the amount of time taken by the function for execution,
#it gives output as hot code / cold code in a tabular form
x = 0
#fname = open('analysis.txt', 'r')
#content = fname.read()
#print content

print "\nHere comes the time of execution of functions:\n"

print "Our definition of hot code and cold code is as follows: Hot Code takes up more than 25% of program execution\n"

print "The functions with less than 25% of execution time form the cold code.\n"

print " Time(in %)  |  Function_name | Self Seconds | Cold Code/Hot Code"

with open('analysis.txt') as fp:
	for line in fp:
		s = ""
		if x>=5 and x<=8:
			s = line[:6]
			print s + "           ",
			print line[54:59] + "          ",
			print line[21:30] + "       ",
			nums = float(s)
			if nums < 25:
				print "Cold Code"
			else:
				print "Hot Code"
		x = x+1
fp.close()

print "\nA detailed analysis of the output can be found in the analysis.txt dump generated by sysprof tool."
print "\nDo you want to see the full detailed output? yes to continue and no to exit!"

c = raw_input()

if(c=="yes"):
	fname = open("analysis.txt", "r")
	content = fname.read()
	print content
else:
	exit(0)

